project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: true
  page-footer: "Copyright 2023, Khushant Khurana"
  title: "Khushant Khurana"
  navbar:
    search: true
    background: dark
    foreground: light
    alignment: center
    pinned: true
    right:
      - text: "Resume"
        href: resume_khurana.pdf
      - text: "Transcript"
        href: transcript.pdf
  sidebar:
    style: docked
    type: light
    background: light
    foreground: dark
    alignment: center
    pinned: true
    border: true
    collapse-level: 2
    
    
    contents:
      - section: "Home"
        contents: 
          - text: "Introduction"
            href: index.qmd
      - section: "Courses taken"
        contents: 
          - text: "- Freshmen year"
            href: freshmen.qmd
          - text: "- Sophomore year"
            href: sophomore.qmd
          - text: "- Junior year"
            href: junior.qmd
          - text: "- Senior year"
            href: senior.qmd
      - section: "Projects"
        contents:
          - text: "- Guidance Navigation & Control"
            href: gnc.qmd
          - text: "- Dynamics & Control"
            href: dynamics_control.qmd
          - text: "- Simulation & Analysis"
            href: simulation.qmd
          - text: "- Mechanical Design & Fabrication"
            href: fabrication.qmd
      - section: "Past internships"
        contents:
          - section: "Controls Intern"
            contents:
              - text: "Poster"
                href: oshkosh_poster.pdf 

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full
editor: visual