project:
  type: website
  output-dir: docs

website:
  back-to-top-navigation: false
  google-analytics: "G-R5DWCF4Z6W"
  page-footer: "Copyright 2023, Khushant Khurana"
  title: "Khushant Khurana"
  navbar:
    search: true
    background: dark
    foreground: light
    alignment: center
    pinned: true
    right:
      - text: "Resume"
        href: resume_khurana.pdf
      - text: "Transcript"
        href: transcript.pdf
  sidebar:
    style: docked
    type: light
    background: light
    foreground: dark
    alignment: center
    pinned: true
    border: true
    collapse-level: 2
    
    
    contents:
      - section: "**Home**"
        class: "section-heading"
        contents: 
          - text: "\u2022 Introduction"
            href: index.qmd
      - section: "**Past internships**"
        class: "section-heading"
        contents:
            - text: "\u2022 Aviation Systems Engineer Intern @ Garmin"
            - text: "\u2022 Controls Intern @ Oshkosh Corporation"
              href: oshkosh_poster.pdf 
      - section: "**Projects**"
        class: "section-heading"
        contents:
          - text: "\u2022 Guidance Navigation & Control"
            href: gnc.qmd
          - text: "\u2022 Dynamics & Control"
            href: dynamics_control.qmd
          - text: "\u2022 Simulation & Analysis"
            href: simulation.qmd
          - text: "\u2022 Mechanical Design & Fabrication"
            href: fabrication.qmd
      
            
            

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full
editor: visual